" Keep 1000 items in the history
set history=1000

" Show the cursor potition
set ruler

" Show incomplete commands.
set showcmd

" Shows a menu while using tab completion
set wildmenu

" For z+Enter to keep at least 5 lines at the top while repositioning the cursor
set scrolloff=5

" Set highlighting text while searching
set hlsearch

" Highlight the matching string while I am performing a search
set incsearch

" Make search case insensitive
set ignorecase

" Make search smart to cases by matching uppercase letters if uppercase letters are used in the pattern
set smartcase

" Save a backup copy of the file before saving
" set backup


set shiftwidth=4
set tabstop=4

" Do not break lines
set nowrap

" If have to break lines in some cases, make sure the words not break in the mid way
set lbr

" Set auto indent for coding
set ai

" Be smart while auto indenting
set smartindent

" Set background to light
"set bg=light

" Set background to dark
" set bg=dark


" Show line numbers
set number

"Set a colorscheme. Custom colorschemes are located inside ~/.vim/colors
colorscheme atom

" map KEY KEYSTROKES
" map <F3> i<ul><CR><Space><Space><li></li><CR><Esc>0i</ul><Esc>kcit
" map <F4> <Esc>o<li></li><Esc>cit 
map <C-b> :NERDTree<CR>
inoremap <C-b> <Esc>:NERDTree<CR>

syntax on
inoremap jj <Esc>
inoremap JJ <Esc>

call plug#begin('~/.vim/plugged')

    Plug 'dense-analysis/ale'
    Plug 'preservim/nerdtree'
    Plug 'codota/tabnine-vim'
    Plug 'frazrepo/vim-rainbow'
    Plug 'junegunn/rainbow_parentheses.vim'



call plug#end()